# Generated by Django 5.2 on 2025-04-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='owner',
        ),
    ]
