# Generated by Django 5.0.3 on 2025-04-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cell', models.CharField(max_length=30)),
                ('picture', models.URLField()),
                ('thumbnail_picture', models.URLField()),
                ('nationality', models.CharField(max_length=10)),
            ],
        ),
    ]
