# Generated by Django 5.0.3 on 2025-04-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='john', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='doe', max_length=255),
        ),
    ]
