# Generated by Django 5.0.3 on 2025-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_person_first_name_alter_person_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='killer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
