# Generated by Django 5.0.3 on 2025-04-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_case_killer'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='alibis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='justification',
            field=models.TextField(blank=True),
        ),
    ]
