# Generated by Django 5.0.3 on 2025-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_case_alibis_case_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='character',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
