# Generated by Django 5.0.3 on 2025-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_case_background_story_case_cause_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_red_herring',
            field=models.BooleanField(default=False),
        ),
    ]
