# Generated by Django 5.0.3 on 2025-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_case_is_red_herring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_red_herring',
        ),
        migrations.AddField(
            model_name='clue',
            name='is_red_herring',
            field=models.BooleanField(default=False),
        ),
    ]
