# Generated by Django 5.2 on 2025-04-24 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evidence'),
        ('api', '0014_remove_case_is_red_herring_clue_is_red_herring'),
    ]

    operations = [
    ]
