# Generated by Django 5.2 on 2025-04-25 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20250424_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='text',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='type',
        ),
        migrations.AddField(
            model_name='evidence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='description',
            field=models.TextField(default='Placeholder description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='title',
            field=models.CharField(default='Placeholder title', max_length=255),
            preserve_default=False,
        ),
    ]
