# Generated by Django 5.2 on 2025-04-25 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_evidence_text_remove_evidence_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victim_cases', to='api.person'),
        ),
    ]
