# Generated by Django 5.2 on 2025-05-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_case_victim'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinstance',
            name='guesses_made',
            field=models.IntegerField(default=0),
        ),
    ]
