# Generated by Django 5.0.3 on 2025-05-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_caseinstance_guesses_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinstance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
